### ISSUE TITLE
Printing the feedback in the console during the processing

### ISSUE THREAD

**Issue by jdlom** [r-spatial/qgisprocess#185]
### Description of the requested feature

Hi,
First of all, thank you so much for this amazing package. It gives us the robustness of many geoalgorithms from differents providers.
`qgisprocess` gives feedback during the processing.
I thought the `.quiet = FALSE` will print the log messages, but it only prints the json parameters before doing the job.
Some of providers like saga have very long treatments, and it would be nice to have this feature, even if I don't know if it's feasible.

**Comment by florisvdh** [comment]
Thanks for bringing this up @jdlom. We do print the `qgis_process` progress bar if there is one, like:

`0...10...20...30...40...50...60...70...80...90...`

However `qgis_process` itself (part of QGIS) currently only shows this bar when it doesn't use JSON input (which uses a JSON parameters string from standard inpu) nor JSON output (returning the JSON string that you see with `.quiet = FALSE`). By default {qgisprocess} calls `qgis_process` with JSON input and output. If you run:

```r
options(qgisprocess.use_json_input = FALSE)
options(qgisprocess.use_json_output = FALSE)
qgis_configure()
```

... then you will have the behaviour you want if you add `.quiet = FALSE`, but since not all algorithms are well supported without JSON, JSON input/output is default and at some point the older behaviour may get unsupported.

Anyway, showing the progress bar in all cases seems like a good idea for a feature request at QGIS. (I plan to point it out)

**Comment by florisvdh** [comment]
Forwarded to https://github.com/qgis/QGIS/issues/55692.

**Comment by florisvdh** [comment]
> ```r
> options(qgisprocess.use_json_input = FALSE)
> options(qgisprocess.use_json_output = FALSE)
> qgis_configure()
> ```

The follow-up of #195 (`json` branch) should bring this down to just `options(qgisprocess.use_json_output = FALSE)` followed by running an algorithm, which will respect the setting without it being stored persistenly in the cache file (still needing `qgis_configure()` to do the latter).
